[platformio]
default_envs = nodemcuv2
src_dir = .

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter =
  +<*>
  -<arduino-build/>
  -<arduino-sketch/>
  -<.pio/>
build_flags =
  -I${PROJECT_DIR}
  -ffunction-sections
  -Wl,--gc-sections
extra_scripts = pre:scripts/generate_version_header.py
monitor_speed = 115200
lib_ldf_mode = deep+